language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.4
  - 2.5.1

gemfile:
  - gemfiles/rake10.gemfile
  - gemfiles/rake11.gemfile

before_install:
  - gem install bundler -v '~> 1.11' --no-ri --no-rdoc
